# SwiftLint configuration
# https://swiftlint.readthedocs.io

# Rules that conflict with swift format's default style
disabled_rules:
  - closure_parameter_position
  - for_where
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - opening_brace
  - trailing_comma

included:
  - Cordierite

type_body_length:
  warning: 600
  error: 700

file_length:
  warning: 700
  error: 800

line_length:
  warning: 120
  error: 200
